/* Crie um programa que pergunte o nome do usuário e peça para este usuário digitar 3
números, o programa deve imprimir, no formato de um objeto, o nome e os números
informados.
*/

let rs = require('readline-sync')

let nomeUsuario = rs.question('Qual o seu nome ? ')
let numero1 = rs.question('Digite um número: ')
let numero1 = rs.question('Digite um número: ')
let numero1 = rs.question('Digite um número: ')

usuario1.nome = nomeUsuario1
usuario1.numerosEscolhidos = [numero1, numero2, numero3]

console.log(usuario1)
