function funcao (){
    let teste = 'Isso é um teste'

}
funcao()
console.log(teste)


//b) Declare uma variável dentro de um bloco (if, else, for, etc.) e tente acessar a mesma

var numeroMaior = 5
var numeroMenor = 3

if(numeroMaior > numeroMenor){

}
console.log(numeroMaior)

//c) Declare duas vezes a mesma variável no mesmo escopo

let faustao = 'oloco'


let faustao = 'oloco bicho'
let outroFausto = 'está fera ai meo'

console.log()
console.log()