//(OBRIGATÓRIO) Faça uma programa que receba 4 notas e calcule a mediana e
//apresente ao usuário o resultado.
//Utilize o pacote : https://www.npmjs.com/package/median

//var user = require('redline-sync')

var modulo = require('./meu_modulo');
//modulo.moduloClauleNotas();
//modulo.moduloCalculeImc();
//modulo.moduloParouImpar();
//modulo.moduloEprimo();
//modulo.moduloSuaIdade();
 
var  cont = 0;
for (var i= 0 ; i<10; i++){
    cont +=5;
    console.log(i)
}
console.log (cont);
typeof cont;