// A
function minhaVar() {
    let nome = 'Bruno';
}
console.log(nome)
// B
if (nome === nome) {
    let nome = 'Isso é inválido';
}
else {
    let erro = 'Isso dará erro!';
}
console.log(texto);
console.log(erro);
// C
let nome = 'Bruno';
let nome = 'Barbosa'
console.log(nome);
// D
let nome = 'Bruno';
function meuNome () {
    let nome = 'Paulo';
}
console.log(nome);
meuNome();
// E
let meuNome = 'true';
let meuBloco = {
    let bloco = 'true';
}
console.log(meuBloco)
// F
let nome = 'Bruno';
nome = 'João';

console.log(nome);