   //OBRIGATÓRIO) Crie um programa que receba uma palavra e exiba quantas
   //consoantes e vogais essa palavra tem.
   //EX : saúde
   //2 consoantes
  //3 vogais

 
 

  var  readlineSync = require('readline-sync');


palavra = 'saúde';
var vogal = ['a','e','i','o','u','ú' ];
let i= 0
let comparacao =[]
var tamanhopalavra = palavra.length
resultado ='';

  
        
  for(i ; i <tamanhopalavra;  i++){
       let caracter = palavra[i];
       let contemVogal = palavra[index](caracter) > -1;

       console.log(caracter);
       caracter = resultado;
    


      // if (caracter = vogal){
        
        // console.log("Numero de vogais: " , caracter{};

       }

       //else if (contemVogal){
       // console.log("Numero de consoantes: " , caracter.length());



 // }
  
//}

    


    


        
   
    