let rs = require('readline-sync')

let tamanhoDasListas = 5

let nomeJogadorA = rs.question('Fale 5 números de 1 a 10: ')
let nomeJogadorB = rs.question('Fale 5 números de 1 a 10: ')

console.clear(
let listaJogadorA = []
for (let i = 0; i < tamanhoDasListas; i < tamanhoDasListas; i++) {
let respostaJogador = 0

while (respostaJogador < || respostajogador > 10) {

let numerosDiferentes = []
for(let i = 0; i < tamanhoDasListas; i < tamanhoDasListas; i++) {
for(let j = 0; j < tamanhoDasListas; j++) {
let itemLista2 = listaJogadorA[j]
let achouNumeroDiferente = itemLista1 === itemLista2if (achouNumeroDiferente) {
let numeroNaoEstaInclusoNaLista = !numerosRepetidos.includes(itemLista1) {
if (numeroNaoEstaInclusoNaLista) {
numerosRepetidos.push(itemLista1)
            }
        }
    }
}

